### ISSUE TITLE
More directions on set up?

### ISSUE THREAD

**Issue by naomi789** [scriptin/jmdict-simplified#11]
I don't have much experience with gradle and I'm having a hard time getting this set up. Could you add directions for how to get started? I'm getting the message "FAILURE: Build failed with an exception." and "Could not determine java version from '12.0.1'" when I run "./gradlew tags" or "./gradlewtasks"

README said 'Java8+', but I'm wondering if this is not compatible with the newest version of Java, or if I skipped a step when setting up gradle.

**Comment by scriptin** [comment]
Hello,

There is no setup, you literally only need Java on your system. I believe you've had this problem because the Gradle wrapper provided within the project used an old version of Gradle, so I've pushed an update, now it uses Gradle 5.4.1 (see [release notes on JDK12 support](https://docs.gradle.org/5.4.1/release-notes.html#support-for-jdk12)), so you may pull and try again.

If you simply need the resulting files, just use the [latest release](https://github.com/scriptin/jmdict-simplified/releases/latest).

**Comment by naomi789** [comment]
Thanks so much!!
