### ISSUE TITLE
Usually Kana

### ISSUE THREAD

**Issue by superchoby** [scriptin/jmdict-simplified#21]
Hello, I noticed that the UK tag is omitted from the json. Is there a way that can be added in?

**Comment by scriptin** [comment]
Hello.

I've just checked that this tag is still present in the latest build, as a lower-case `"uk"`:

```bash
% grep -o '"uk":"word usually written using kana alone",' jmdict-all-3.2.0-alpha.1.json
"uk":"word usually written using kana alone",
```

Maybe it's because you're using the upper-case `"UK"` instead of `"uk"`? The JSON files were not updated for a long time (before I released the new conversion script a few days ago), so I guess the authors of the original JMdict XML files might have changed some spelling.

Let me know if that helps.
