### ISSUE TITLE
[Feature Request] Support for JMdict_e_examp

### ISSUE THREAD

**Issue by OneSidedPrism** [scriptin/jmdict-simplified#31]
Hi there,

First of all, huge thank you for putting this together. 

I noticed there is [an official JMdict release called "JMdict_e_examp" which includes example sentences for each entry.](https://www.edrdg.org/wiki/index.php/JMdict-EDICT_Dictionary_Project#CURRENT_VERSION_&_DOWNLOAD). My feature request is to have this added to your JSON releases. My use case is that I'm using your JSON to build Anki flashcards, and having access to some example sentences for a given word would be helpful to include with each card.

**Comment by scriptin** [comment]
Hello @OneSidedPrism 👋🏻 

I will take a look at it later today and give you a rough estimate on when I can add that.

**Comment by scriptin** [comment]
Okay, this seems fairly simple. I will try to add this this week.

**Comment by scriptin** [comment]
Hey @OneSidedPrism, I'm mostly done adding this feature, but I have a question...

So, in the version history of JMdict I see this entry:

```
<!-- Rev 1.08
        Delete <info> and <example> elements
-->
```

As I understand, they've removed this field on purpose. Now, I have several options to fulfill your request:

1. Add "examples" field in all versions of JMdict JSON files in this project. The downside is that it will be empty for most of entries, increasing the size of files for everyone, and potentially breaking someone's scripts.
2. Create a new, separate version of JSON file. Same as existing ones, but with this new field. The downside is that it will be unsupported by Node.js libs which are the part of this project. I can add the support, but since nobody is using it now, and you're the only one yet who needs this feature, I don't see a reason to do this extra work. Besides, I assume you're probably using Python to build your flashcards and thus you don't care about Node.js libraries (correct me if I'm wrong).
3. Put examples in a separate file with simpler structure, e.g. only entry id and examples. This will still be fairly easy to parse, and it will not change anything else, thus keeping backwards-compatibility for everyone.

**The question: are you okay with Option 3?**

I think it's the best way to move forward considering all pros and cons. I understand that it will complicate your scripts, but probably not too much. Since even the authors of original XML files decided to delete this field, I think it's best to preserve maximum compatibility with the main version, so I would not do the Option 1.

---

For your information, there are not a lot of these examples:

```
> grep '<example>' build/dict-xml/JMdict_e_examp.xml | wc -l
   31922
```

There are 210055 entries total for English, so only about 15,2% of them have examples. I suppose they added examples for the common ones, but in any case this field will be mostly empty.

**Comment by scriptin** [comment]
BTW, if you want to try it right now, or in case if you only need this once, I have a branch with a working converter here: https://github.com/scriptin/jmdict-simplified/tree/jmdict-examples

You can clone the repo, checkout the `jmdict-examples` branch, and run these in your shell:

```shell
./gradlew download
./gradlew jmdictExamplesConvert
```

Then, you can find the converted version in `build/dict-json/jmdict-eng-3.5.0.json`. It will have the additional field inside the `sense` elements:

```json
"examples": [
  {
    "source": {"type":"tatoeba","value":"234521"},
    "text": "あからさまに",
    "sentences": [
      {"land":"jpn","text":"あからさまに言えば彼は嫌いだ。"},
      {"land":"eng","text":"Frankly, I don't like him."}
    ]
  }
]
```

**Comment by scriptin** [comment]
Or just grab this, actually:
[jmdict-eng-examples-3.5.0.json.tar.gz](https://github.com/user-attachments/files/17035074/jmdict-eng-examples-3.5.0.json.tar.gz)

**Comment by OneSidedPrism** [comment]
Option 3 is totally fine! I am parsing out the ID field for each lookup, so it'll be easy enough to send it back through another dictionary with just the example sentences. You are correct in assuming that I'm building the script in Python :)

Interesting to see that most entries don't have examples, and to see that it doesn't include a tatoeba link or reference#. Are you familiar with [Jitendex](https://github.com/stephenmk/Jitendex)? I did some digging in his JSON and found that he actually has the tatoeba.org link included in his data, though I'm not sure how he linked each JMDict entry with the tatoeba entry.

However, his JSON is built specifically for Yomitan, so it's not nearly as convenient to parse as the JSON you provide in this repo!

**Comment by scriptin** [comment]
Okay, I'll do option 3 then. I'll need a couple days for adjusting the scripts and release process.

> Interesting to see that most entries don't have examples

I expected that, since example sentences are from Tanaka corpus, which is relatively small.

> and to see that it doesn't include a tatoeba link or reference#

I'm not sure if I understand you correctly. Examples, when present, have reference IDs for Tatoeba. In the example above, `"source": {"type":"tatoeba","value":"234521"},` where `234521` is the sentence ID, and here's the sentence: <https://tatoeba.org/en/sentences/show/234521>

> Are you familiar with [Jitendex](https://github.com/stephenmk/Jitendex)?

No, I haven't seen it before. Looks interesting, I'll definitely check it out. Thank you for this information!

**Comment by OneSidedPrism** [comment]
Ah! I didn't look hard enough at the fields you showed. Glad to see it does have that tatoeba ID.

Thanks again for taking my feature request 🙂

**Comment by scriptin** [comment]
I ended up implementing the option 2 instead, so you'll have a single file to work with.

The main reason for that is that examples are actually contained within `sense` elements, which I haven't realized at first. These `sense` elements can have different part-of-speech fields within a single dictionary entry, and also some of them only apply to certain spellings (see `appliesToKanji` and `appliesToKana` fields), which complicates things.

I would have to include not only examples themselves, but also at least partially their parent `sense` elements, so that it would be possible to tell which particular `sense` in used in each example. I hope I managed to explain the problem, but here's a graph just in case:

```
entry
  - id
  - kanji[]
  - kana[]
  - sense[] // array of possible senses
    - partOfSpeech[] // noun, verb, etc.
    - appliesToKanji[]
    - appliesToKana[]
    - ...
    - examples[] // <-- examples are nested in `sense`
                 // to preserve this relationship, I would need to keep 
                 // the parent `sense` element with some of its fields
```

I would have to keep `sense` elements with at least some fields (probably `partOfSpeech`, `appliesToKanji`, `appliesToKana`, and maybe something else), so that you could tell which example is from which sense. And it's quite a lot of stuff to keep an eye on, both on my and on your side. I think it's just too error-prone, since it would possible to mismatch examples and senses. Not all senses have examples, so there would have to be an algorithm for matching them properly.

---

Here are example files for you to try. They have the exact same structure, except for additional `examples` field inside `sense`.

[jmdict-examples-eng-3.5.0.json.tgz](https://github.com/user-attachments/files/17062897/jmdict-examples-eng-3.5.0.json.tgz)
[jmdict-examples-eng-3.5.0.json.zip](https://github.com/user-attachments/files/17062899/jmdict-examples-eng-3.5.0.json.zip)

Please let me know if this works for you, and if there are no issues, I'll merge this branch. It's pretty much ready, except the docs.

**Comment by OneSidedPrism** [comment]
Awesome! I think the approach you took makes the most sense, then (no pun intended). I'll test out a few queries with the example files you shared and let you know if I run into any issues.

**Comment by scriptin** [comment]
@OneSidedPrism I was really busy and a bit sick, but finally I've done it! Check out [the latest release](https://github.com/scriptin/jmdict-simplified/releases/tag/3.6.1%2B20241012152656). All next releases will also include this, of course.

**Comment by OneSidedPrism** [comment]
No worries at all @scriptin! Thanks for taking my request!
